[package]
name = "tauri-plugin-graphql"
version = "0.0.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.57"
exclude = ["/examples"]

[dependencies]
juniper = { version = "0.15.9", default-features = false }
serde_json = "1.0.79"
tauri = { version = "1.0.0-rc.6" }

[dev-dependencies]
rand = "0.8.5"

[features]
chrono = ["juniper/chrono"]
url = ["juniper/url"]
uuid = ["juniper/uuid"]