name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: next-7
          run_install: true
      - name: covector status
        uses: jbolda/covector/packages/action@covector-v0
        with:
          command: 'status'
